### ISSUE TITLE
How can I make the browser full screen automatically?

### ISSUE THREAD

**Issue by GroundWalker7** [netsurf-browser/netsurf#2]
When the browser is opened, I want it to be full screen.
I tried to set kiosk_mode to `true`, but it doesn't work.
`NSOPTION_BOOL(kiosk_mode, false)`

**Comment by rjek** [comment]
We don't use GitHub issue tracking, please file bugs at https://bugs.netsurf-browser.org/ or request support from the mailing list http://www.netsurf-browser.org/contact/#MailingLists
